name: "Cloudfront Lambda Edge version Update"
description: "Update lambda edge version in cloudfront distribution"
author: elseu
branding:
  icon: "terminal"
  color: "red"
inputs:
  distribution_id:
    description: "Cloudfront Distribution Id"
    required: true
  path_pattern:
    description: "Cloudfront Behavior Path pattern"
    required: true
  lambda_association_event_type:
    description: "Event type"
    required: true
  lambda_association_version_arn:
    description: "New Lambda version ARN"
    required: true
runs:
  using: docker
  image: Dockerfile