name: "Cloudfront Lambda Edge version Update"
description: "Update lambda edge version in cloudfront distribution"
author: elseu
branding:
  icon: "terminal"
  color: "red"
inputs:
  distribution_id:
    description: "Cloudfront Distribution Id"
    required: true
  lambda_viewer_request_version_arn:
    description: "New Lambda Viewver Request version ARN"
    required: false
  lambda_origin_request_version_arn:
    description: "New Lambda Origin Request version ARN"
    required: false
  lambda_origin_response_version_arn:
    description: "New Lambda Origin Response version ARN"
    required: false
  lambda_viewer_response_version_arn:
    description: "New Lambda Viewer Response version ARN"
    required: false
runs:
  using: docker
  image: Dockerfile