name: "Cloudfront Lambda Edge version Update"
description: "Update lambda edge version in cloudfront distribution"
author: elseu
branding:
  icon: "terminal"
  color: "red"
inputs:
  distribution_id:
    description: "Cloudfront Distribution Id"
    required: true
  path_pattern:
    description: "Cloudfront Behavior Path pattern"
    required: true
  lambda_association_event_type:
    description: "Event type"
    required: true
  lambda_association_version_arn:
    description: "New Lambda version ARN"
    required: true
  cloudfront_invalidation_required:
    description: "Enable to invalidate Cloudfront cache"
    required: true
  aws_region:
    description: "AWS region to execute action"
    required: false
  aws_access_key:
    description: "AWS access key to execute action"
    required: false
  aws_secret_key:
    description: "AWS secret key to execute action"
    required: false
runs:
  using: docker
  image: Dockerfile